Everything is okay

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -42,9 +42,9 @@ function install_ninja() {
   (
     echo "∗ Downloading and installing ninja..."
     curl --silent --location --create-dirs --output "${install_path}/bin/ninja.zip" "$download_url" || fail "Could not download ninja $version"
-    unzip "${install_path}/bin/ninja.zip" || fail "Could not uncompress"
+    unzip "${install_path}/bin/ninja.zip" -d "${install_path}/bin" >/dev/null || fail "Could not uncompress"
     chmod +x "${install_path}/bin/ninja" || fail "Could not find uncompressed ninja binary"
-    rm -rf "${install_path}/bin/ninja.zip"
+    rm "${install_path}/bin/ninja.zip" || fail "Could not remove zip file"
 
     echo
     echo "=================================================="
